version: "3"

services:
  shop:
    container_name: shop
    image: shopware/development:8.2-composer-2
    ports:
      - "80:80"
      - "8888:8888" # Administration watcher
      - "9999:9999" # Storefront watcher
    volumes:
      - ./shopware:/app
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1

  database:
    container_name: database
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    volumes:
      - "database_volume:/var/lib/mysql"
    networks:
      - web
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=shopware
      - MYSQL_PASSWORD=shopware
      - MYSQL_DATABASE=shopware

volumes:
  database_volume:
    driver: local

networks:
  web:
    external: false
