version: '3'

# ----------------------
# Services configuration
# ----------------------
services:
  latex:
    container_name: latex
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - "./src:/src"
      - "./dev-ops:/dev-ops"
      - "./build:/build"
